import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
// THEME PROVIDER
import CustomThemeProvider from '@/theme/theme-provider';
import { LoadingProgress } from '@/components/loader';
import SettingsProvider from '@/contexts/settingsContext';
import RTL from '@/components/rtl';
import { esES } from '@clerk/localizations'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Tricks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  
  return (
    <ClerkProvider localization={esES}>
      <html lang="es">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SettingsProvider>
            <CustomThemeProvider>
              <LoadingProgress />
              <RTL>{children}</RTL>
            </CustomThemeProvider>
          </SettingsProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}